### ISSUE TITLE
Failed to build keyboard layouts map!

### ISSUE THREAD

**Issue by stsg** [lyokha/g3kb-switch#1]
Gnome version 3.34.2 on X.org

❯ ./g3kb-switch -v
g3kb-switch version 0.1

❯ ./g3kb-switch -l    
Failed to build keyboard layouts map!

❯ ./g3kb-switch -n
Failed to build keyboard layouts map!

❯ ./g3kb-switch -s us
Failed to build keyboard layouts map!

**Comment by lyokha** [comment]
```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().currentSource.id"
```

What is the output of this command in your terminal?

**Comment by stsg** [comment]
(true, '"us"')
or
(true, '"ru+phonetic"')

**Comment by lyokha** [comment]
Hmm, then it must work. Probably you tried this in a guest login shell, say being logged in as a superuser? (Кстати, можно по-русски, если вам удобнее.)

**Comment by stsg** [comment]
Ok ;)
ArchLinux
Работаю в терминале, от своего имени:

> uid=1000(sts) gid=1000(sts) groups=1000(sts),998(wheel)

❯  ldd g3kb-switch    
> 	linux-vdso.so.1 (0x00007ffeea3ec000)
> 	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f165bf9e000)
> 	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f165bf42000)
> 	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f165be1d000)
> 	libc.so.6 => /usr/lib/libc.so.6 (0x00007f165bc56000)
> 	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f165bc51000)
> 	libz.so.1 => /usr/lib/libz.so.1 (0x00007f165bc37000)
> 	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f165bbd5000)
> 	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f165bbbc000)
> 	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f165bb9a000)
> 	libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f165bb8f000)
> 	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f165bb1c000)
> 	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f165c19a000)
> 	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f165bb17000)
> 	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f165babf000)
> 	librt.so.1 => /usr/lib/librt.so.1 (0x00007f165bab4000)

**Comment by stsg** [comment]
Не делал
> make install
думаю не принципиально?

**Comment by lyokha** [comment]
Да, не принципиально. Вот прямо сейчас не могу сказать почему у вас не работает. Раз работает D-Bus, то должен работать и свитчер. Наверное придется добавить более развернутые сообщения об ошибках в программу, чтобы выяснить что конкретно сбоит.

**Comment by stsg** [comment]
Ok, помогу, чем смогу ;)
Очень не хватает vim-xkbswitch (

**Comment by lyokha** [comment]
Я закоммитил изменения с деталями ошибок для D-Bus соединения. Если вы обновите, и попробуете снова `./g3kb-switch -p`, то, если дело в D-Bus, вы увидите еще одно строку с `Error details`, если не увидите, то дело не в D-Bus и я добавлю другие сообщения.

**Comment by stsg** [comment]
Дело видимо не в D-Bus:

> ❯ ./g3kb-switch -p
> Failed to build keyboard layouts map!

**Comment by lyokha** [comment]
Ок, сейчас для всего детали ошибок повставляю ))

**Comment by lyokha** [comment]
Но вы меня не ждите, ведь поздно уже!

**Comment by stsg** [comment]
Ok, спасибо. С утра буду реагировать )

**Comment by lyokha** [comment]
Добавил описания ошибок на все действия. Можете проверять.

**Comment by stsg** [comment]
> ❯ ./g3kb-switch -p
> Failed to build keyboard layouts map!
> Error details: Failed to parse response value

**Comment by lyokha** [comment]
Интересно. А что у вас показывает такая замысловатая длинная команда?

```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "ids = [];for (i in imports.ui.status.keyboard.getInputSourceManager().inputSources){ids.push({key:i, value:imports.ui.status.keyboard.getInputSourceManager().inputSources[i].id})};ids"
```

Это и есть основной JS метод получения списка раскладок. Судя по логу, он возвращает у вас false в первом элементе кортежа.

**Comment by lyokha** [comment]
Благодаря ответу @Galicarnax, кажется понятно в чем здесь дело, я закоммитил исправления, проверьте пожалуйста.

**Comment by stsg** [comment]
Отлично! Спасибо!
Работает. vim-xkbswitch тоже заработал.
