### ISSUE TITLE
Не работает на Ubuntu 22.04.1

### ISSUE THREAD

**Issue by gitislab** [lyokha/g3kb-switch#10]
Ubuntu 22.04.1 LTS
64-bit
Gnome 42.4 Wayland

Как ни старался, не завелся. Установил по иструкции, в том числе и плагин, но не завелось.
запуск от user:
> user@ubuntu:~$ g3kb-switch -l
> Failed to build keyboard layouts map: Bad response: 

запуск с sudo:
> user@ubuntu:~$ sudo g3kb-switch -l
> Failed to build keyboard layouts map: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell was not provided by any .service files

проверка:
> user@ubuntu:~$ gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List
> Ошибка: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Объект по пути «/org/g3kbswitch/G3kbSwitch» не существует

**Comment by lyokha** [comment]
Вам нужно убедиться, что Gnome extension G3kbSwitch установлен и включен.

**Comment by gitislab** [comment]
включил, но поведение не изменилось

> user@ubuntu:~$ gnome-extensions enable g3kb-switch@g3kb-switch.org
> user@ubuntu:~$ gnome-extensions list
> g3kb-switch@g3kb-switch.org
> ding@rastersoft.com
> ubuntu-appindicators@ubuntu.com
> ubuntu-dock@ubuntu.com
> user@ubuntu:~$ g3kb-switch -l
> Failed to build keyboard layouts map: Bad response: 
> user@ubuntu:~$

**Comment by lyokha** [comment]
Что говорит `gnome-extensions list --enabled`?

**Comment by gitislab** [comment]
> 

> user@ubuntu:~$ gnome-extensions list --enabled
> g3kb-switch@g3kb-switch.org
> ding@rastersoft.com
> ubuntu-appindicators@ubuntu.com
> ubuntu-dock@ubuntu.com
>

**Comment by lyokha** [comment]
Если эктеншн установлен и включен, то команда `gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List` не должна выводить `Ошибка: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Объект по пути «/org/g3kbswitch/G3kbSwitch» не существует`.

**Comment by gitislab** [comment]
видимо да, сейчас выводит:

> user@ubuntu:~$ gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List
> (true, '[{"key":"0","value":"us"},{"key":"1","value":"ru"}]')

**Comment by lyokha** [comment]
А вы точно с флагом cmake `-DG3KBSWITCH_WITH_GNOME_SHELL_EXTENSION=ON` собирали?

**Comment by gitislab** [comment]
Ну точно, собирал без флага, спасибо!

**Comment by lyokha** [comment]
Если заработало, то закрывайте баг, ну или я позже сам закрою.

**Comment by lyokha** [comment]
Я сделал `-DG3KBSWITCH_WITH_GNOME_SHELL_EXTENSION=ON` флагом по умолчанию, так как это необходимо для сборки с *Gnome 41* и выше, и мало где остались версии *Gnome 3.x*. Так что теперь не обязательно указывать его при сборке для новых Gnome. Также соответственно обновил документацию.

**Comment by Rom888** [comment]
It works on my Ubuntu 22.04.1 too. Thank you for this project!
