### ISSUE TITLE
[TYPO] libglib2.0 should be libglib2.0-0

### ISSUE THREAD

**Issue by sergeolkhovik** [lyokha/g3kb-switch#23]
Hi! Currently using another method to select needed keyboard layout:
```
exec gdbus call --session --dest org.gnome.Shell \
    --object-path /dev/ramottamado/EvalGjs \
    --method dev.ramottamado.EvalGjs.Eval \
    "imports.ui.status.keyboard.getInputSourceManager().inputSources[$1].activate()"
```
(found at reddit). But looks like this won't work if I upgrade to 23.10 and thus get Gnome 45.
So I decided to try your tool and get this error while installing the deb:
```
cmake -Bbuild -DG3KBSWITCH_WITH_LEGACY_GNOME_SHELL_EXTENSION=ON
-- The C compiler identification is GNU 12.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for one of the modules 'gio-2.0'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    G3KBSWITCH_WITH_LEGACY_GNOME_SHELL_EXTENSION


-- Build files have been written to: /home/serge/src/g3kb-switch-1.3/build
-----------------------------------------------------------------------------------------------------------------------------------------------------
cmake --build build
[ 14%] Building C object CMakeFiles/g3kb-switch.dir/main.c.o
[ 28%] Building C object CMakeFiles/g3kb-switch.dir/switch.c.o
[ 42%] Linking C executable g3kb-switch
[ 42%] Built target g3kb-switch
[ 57%] Building C object CMakeFiles/g3kbswitch.dir/switch.c.o
[ 71%] Building C object CMakeFiles/g3kbswitch.dir/switch-api.c.o
[ 85%] Linking C shared library libg3kbswitch.so
[ 85%] Built target g3kbswitch
[100%] Generating g3kb-switch.1.gz
[100%] Built target man-g3kb-switch
-----------------------------------------------------------------------------------------------------------------------------------------------------
cd build; cpack -G DEB
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: g3kb-switch
CPack: - Install project: g3kb-switch []
CPack: Create package
CPack: - package: /home/serge/src/g3kb-switch-1.3/build/g3kb-switch-1.3-Linux.deb generated.
-----------------------------------------------------------------------------------------------------------------------------------------------------
sudo -E dpkg -i /home/serge/src/g3kb-switch-1.3/build/g3kb-switch-1.3-Linux.deb
Selecting previously unselected package g3kb-switch.
(Reading database ... 383482 files and directories currently installed.)
Preparing to unpack .../g3kb-switch-1.3-Linux.deb ...
Unpacking g3kb-switch (1.3) ...
dpkg: dependency problems prevent configuration of g3kb-switch:
 g3kb-switch depends on libglib2.0; however:
  Package libglib2.0 is not installed.

dpkg: error processing package g3kb-switch (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.11.2-1) ...
Errors were encountered while processing:
 g3kb-switch
```

I see there's libglib2.0-0 lib available (https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libglib2.0&searchon=names):
```
aps libglib2.0
libglib2.0-0 - GLib library of C routines
libglib2.0-bin - Programs for the GLib library
libglib2.0-data - Загальні файли для бібліотеки GLib
libglib2.0-dev - Development files for the GLib library
libglib2.0-dev-bin - Development utilities for the GLib library
libglib2.0-doc - Documentation files for the GLib library
libglib2.0-cil - CLI binding for the GLib utility library 2.12
libglib2.0-cil-dev - CLI binding for the GLib utility library 2.12
libglib2.0-tests - GLib library of C routines - installed tests
```

Can I just update CMakeLists.txt:
```
SET(CPACK_DEBIAN_PACKAGE_DEPENDS libglib2.0)
```
with libglib2.0-0?
Thanks in advance.

**Comment by lyokha** [comment]
@Freed-Wu could you help?

**Comment by Freed-Wu** [comment]
> Can I just update CMakeLists.txt:
> 
> SET(CPACK_DEBIAN_PACKAGE_DEPENDS libglib2.0)
> 
> with libglib2.0-0?

<https://github.com/lyokha/g3kb-switch/blob/master/CMakeLists.txt#L133> has this line.

> Package libglib2.0 is not installed.



In fact, if you install a program by `apt install XXX`, it will install `XXX`s dependencies automatically. If you install a program by `dpkg -i XXX`, you must install `XXX`s depencies by yourself.

So I think this is an expected behaviour.

**Comment by Freed-Wu** [comment]
The better solution is let someone to package this program to PPA in order to let user can `apt install`. This can be a new issue to discuss.

**Comment by Freed-Wu** [comment]
BTW, you can simply think `apt` is a wrapper of `dpkg`. It download `*.deb`, scan its dependencies, install them recursively, and install `*.deb` finally.

**Comment by sergeolkhovik** [comment]
> > Can I just update CMakeLists.txt:
> > SET(CPACK_DEBIAN_PACKAGE_DEPENDS libglib2.0)
> > with libglib2.0-0?
> 
> https://github.com/lyokha/g3kb-switch/blob/master/CMakeLists.txt#L133 has this line.
> 
> > Package libglib2.0 is not installed.
> 
> In fact, if you install a program by `apt install XXX`, it will install `XXX`s dependencies automatically. If you install a program by `dpkg -i XXX`, you must install `XXX`s depencies by yourself.
> 
> So I think this is an expected behaviour.

The problem is that there's no libglib2.0 package that's mentioned at https://github.com/lyokha/g3kb-switch/blob/master/CMakeLists.txt#L133. Instead there's libglib2.0-0 package available in Ubuntu (https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libglib2.0&searchon=names). So that's why I ask if those 2 packages are the same and I can update that line and build proper deb package with the corrected dependency name? Can you tell me what distro that DEB has been installed successfully?
I just checked Debian and don't see libglib2.0 either, and libglib2.0-0 (https://packages.debian.org/bookworm/libglib2.0-0) doesn't provide libglib2.0.

**Comment by sergeolkhovik** [comment]
Can't fnd how  to reopen this issue. Still unresolved.

**Comment by Freed-Wu** [comment]
> The problem is that there's no libglib2.0 package

Oh, `libglib2.0` maybe a typo of `libglib2.0-0`. I saw it wrong.

**Comment by Freed-Wu** [comment]
Can you try <https://github.com/lyokha/g3kb-switch/commit/ef62137e4ca9ad91b1c71a151b27e09691e3de43>?

**Comment by lyokha** [comment]
@Freed-Wu I checked on an Ubuntu laptop that the package name is indeed `libglib2.0-0` I successfully installed a deb package built after applying you fix (while I couldn't before), so the fix is good.

**Comment by Freed-Wu** [comment]
Good. I've changed the title of this issue to make it clearer. Thanks for your report.
