### ISSUE TITLE
Support gnome 45.1

### ISSUE THREAD

**Issue by Freed-Wu** [lyokha/g3kb-switch#24]
![Screenshot from 2023-12-05 21-39-34](https://github.com/lyokha/g3kb-switch/assets/32936898/5f2b011e-5470-478c-83c9-44a4ab84f1cf)

**Comment by lyokha** [comment]
Hmm, this workef with Gnome 45 built without any explicit cmake flags.

**Comment by lyokha** [comment]
```ShellSession
$ gnome-shell --version
GNOME Shell 45.2
$ g3kb-switch --version
g3kb-switch version 1.2
$ g3kb-switch -l
us
ru
```

Works. Only it should be re-installed for Gnome 45. (And also the version 1.2 happened to miss bumping, I'm going to fix this).

**Comment by Freed-Wu** [comment]
The latest version support gnome 45. How about publish a new version?

About forgetting dumption version, Can it get version from git tag when building? It should can solve this problem forever.

**Comment by lyokha** [comment]
A good idea, 1.4? I will also look how to sync the version in main.c automatically.

**Comment by Freed-Wu** [comment]
#25 allow --version use CMakeLists.txt's version.

**Comment by Freed-Wu** [comment]
Do you mind some github action?

**Comment by lyokha** [comment]
Do you mean build and tests? I don't mind!

**Comment by Freed-Wu** [comment]
Do you have a AUR account? Then I'll add you to [AUR](https://aur.archlinux.org/packages/g3kb-switch)

**Comment by Freed-Wu** [comment]
Oh, I think you register a AUR account and add your secret to github will be better. Use mine is not convenient.

**Comment by Freed-Wu** [comment]
Oh, I think you register a AUR account and add your secret to github will be better. Use mine is not convenient.

**Comment by lyokha** [comment]
Ok, I'll register at AUR. What then?

**Comment by Freed-Wu** [comment]
Let me publish a new version and trigger the github action! Now AUR will failed because lack of a secret. It is normal, You can add the secret after and try again.

**Comment by lyokha** [comment]
Could yo help me? I don't have an Arch, but need to answer `LC_ALL=C pacman -V|sed -r 's#[0-9]+#49f#g'|md5sum|cut -c1-6` fo registration (the say this is to protect against bots). Could you type what your computer answer on it?

**Comment by lyokha** [comment]
> Let's publish a new version and trigger the github action! Now AUR will failed because lack of a secret. It is normal, You can add the secret after and try again.

Ok.

**Comment by Freed-Wu** [comment]
See <https://github.com/lyokha/g3kb-switch/actions/runs/7112567468>. deploy-aur is failed due to lack a secret. Add AUR_SSH_PRIVATE_KEY to your secret. It looks like:

```
-----BEGIN OPENSSH PRIVATE KEY-----
XXX
-----END OPENSSH PRIVATE KEY-----
```

Make sure without wrong format.

After github secret is added, no one can see it again, even if you are the one who added the github secret.

**Comment by Freed-Wu** [comment]
See <https://github.com/lyokha/g3kb-switch/actions/runs/7112567468>. A deb and rpm package can be downloaded.

**Comment by lyokha** [comment]
Thanks! I registered at AUR.

**Comment by lyokha** [comment]
@Freed-Wu what should I put as the value of AUR_SSH_PRIVATE_KEY in the secret? Do I take this out of my AUR account?

**Comment by lyokha** [comment]
https://github.com/lyokha/g3kb-switch/actions/runs/7112567468/job/19363901161 : still fails.

**Comment by lyokha** [comment]
Do I need to add also secrets AUR_USERNAME and AUR_EMAIL as advised at https://github.com/KSXGitHub/github-actions-deploy-aur?

**Comment by lyokha** [comment]
@Freed-Wu Just committed https://github.com/lyokha/g3kb-switch/commit/919673ee5489837ff4efbe17fcb79ae0376dde19 with some improvements regarding automatic detection of version. Note that *flake.nix* still contains literal *1.3*, perhaps it can also be automated?

**Comment by Freed-Wu** [comment]
> Note that flake.nix still contains literal 1.3, perhaps it can also be automated?

Sorry for late, the github marketplace have some github workflow about update flake.nix however I've not used. I'll survey them.

> add also secrets AUR_USERNAME and AUR_EMAIL

Shouldn't. Now it works!
