### ISSUE TITLE
Gnome 46 Support

### ISSUE THREAD

**Issue by moskalenco-a** [lyokha/g3kb-switch#28]
Tried this extension with Fedora 40 beta & Gnome 46(before update all worked on Fedora 39 & Gnome 45), in Extensions (GUI utlity) there is message
>The installed version of this extension is incompatible with the current version of GNOME (undefined). The extension has been disabled

As I understand, on every new Gnome version, extension will become non-working, and small fixes (sorry if no) needed ?

**Comment by lyokha** [comment]
Yes, i'll fix this today, you can simply add `46` in *metadata.json* of the extension.

**Comment by Freed-Wu** [comment]
I have tested it can work now. Can we release a new version?

**Comment by lyokha** [comment]
> I have tested it can work now. Can we release a new version?

@Freed-Wu  Yes, sure, please do it!
