### ISSUE TITLE
Не работает на GNOME 42

### ISSUE THREAD

**Issue by anuvyklack** [lyokha/g3kb-switch#7]
Не работает на Ubuntu 22.04 и на Fedora 36.

На запрос
```
gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List
```
получаю
```
Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/g3kbswitch/G3kbSwitch”
```
И в меню расширений висит такое:

![Screenshot from 2022-05-09 19-07-32](https://user-images.githubusercontent.com/13056013/167451441-cb08b4ae-334c-46dc-97fc-26336dcdd144.png)

**Comment by lyokha** [comment]
Как, заработало? Коммит автоматом закрыл багрепорт.
