### ISSUE TITLE
3kbSwitch Gnome Shell extension vs. Lock Screen

### ISSUE THREAD

**Issue by KallistoD** [lyokha/g3kb-switch#8]
I found that 3kbSwitch Gnome Shell extension doesn't work when Lock Screen is active. Please, let me know if there are any ideas how to make it work.

Output when commands executed in terminal manually (3kbSwitch and the extension work fine):
```
$ id
uid=1000(cactus) gid=1000(cactus) группы=1000(cactus),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),134(lxd),135(sambashare),137(vboxusers)
$ gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List
(true, '[{"key":"0","value":"us"},{"key":"1","value":"ru"}]')
```

Output if the same commands executed by a script during active Lock Screen (user session is still active, no logout, 3kbSwitch Gnome Shell doesn't work):
```
$ id
uid=1000(cactus) gid=1000(cactus) группы=1000(cactus),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),134(lxd),135(sambashare),137(vboxusers)
$ gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List
Ошибка: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Объект по пути «/org/g3kbswitch/G3kbSwitch» не существует
```

Some details if necessary:
I'm trying to find a way to automatically switch keyboard layout to English in password input field of Lock Screen. By default, GNOME 42.1 (Ubuntu 22.04 LTS, X11) Lock Screen derives the keyboard layout from the last focused window.
Earlier, I could find Lock Screen activation with dbus-monitor and automatically change my keyboard layout to English (if necessary) with org.gnome.Shell.Eval() method. But this method was disabled for security reasons since GNOME 41. So, I'm trying to find another solution.

**Comment by lyokha** [comment]
It looks like all gnome extensions get disabled when screen gets locked for *security reasons* (tm). See https://stackoverflow.com/questions/47008276/gnome-shell-extensions-preventing-the-call-of-disable-when-the-screen-gets-lo. However, as the answer to the question suggests, you can remove all code from function `disable()` in *extension.js* and try if this works: this will render the extension *insecure* and inappropriate for extension repositories, but who cares.
