### ISSUE TITLE
метод получения списка раскладок выдает (false, '')

### ISSUE THREAD

**Issue by lumpsoid** [lyokha/g3kb-switch#9]
Столько раз споткнулся пока пытался заставить все это работать на Ubuntu 22.04 (GNOME Shell 42.4), но все равно не заработало.

в .vimrc следующее:
```
let g:XkbSwitchEnabled = 1
let g:XkbSwitchLib = '/usr/local/lib/libg3kbswitch.so'
let g:XkbSwitchIMappings = ['ru']
```

переключатель работает:
```
g3kb-switch -n
```
данная комманда переключает раскладку

все команды из проверки работы экстеншена – работают
```
(base) ➜  ~ gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.List
(true, '[{"key":"0","value":"us"},{"key":"1","value":"ru+typewriter"}]')
(base) ➜  ~ gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.Get
(true, '1')
(base) ➜  ~ gdbus call --session --dest org.gnome.Shell --object-path /org/g3kbswitch/G3kbSwitch --method org.g3kbswitch.G3kbSwitch.Set 1
(true, '')
```
пытаясь найти решение проблемы – в vim ничего не работало
нашел следующий материал – [ссылка](https://github.com/lyokha/g3kb-switch/issues/1)
где говорилось, что основной метод получения картежей, следующий:
```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "ids = [];for (i in imports.ui.status.keyboard.getInputSourceManager().inputSources){ids.push({key:i, value:imports.ui.status.keyboard.getInputSourceManager().inputSources[i].id})};ids"
```
и он выдает у меня
```
(false, '')
```
и я так понимаю, именно из за этого не может заработать vim плагин

спасибо за помощь

**Comment by lyokha** [comment]
Нет, проблема не в этом, последняя команда использует интерфейс *org.gnome.Shell.Eval*, он действительно не работает в Gnome 42.

Как вы собирали g3kb-switch? Для новых гномов в cmake нужно передать особую опцию как описано в Readme.

**Comment by lumpsoid** [comment]
да, я собирал его с использованием параметра экстеншена

сначала установил экстеншен:
```
cd ../extension
make install
```
после чего собрал g3kb-switch:
```
cmake -DCMAKE_BUILD_TYPE=Release -DG3KBSWITCH_WITH_GNOME_SHELL_EXTENSION=ON ..
```
после чего его еще нужно было активировать в GNOME Shell Extensions

**Comment by lyokha** [comment]
Ну, кстати если переключатель работает, значит правильно собрали. В чем-то другом проблема.

**Comment by lyokha** [comment]
Кстати, ваша раскладка называется *ru+typewriter*, а в imappings написано *ru*, правильнее заменить, но это не должно влиять на основную функциональность. Может у вас библиотека не по указанному пути установлена?

**Comment by lumpsoid** [comment]
вы имеете ввиду `/usr/local/lib/libg3kbswitch.so` ?
этот файл проверял, все на месте находится

попробовал поменять на `ru+typewriter`, весь vim в ошибках, поэтому пока верну

**Comment by lyokha** [comment]
Что у вас напишет vim, если ввести ` :echo libcall(g:XkbSwitch['backend'], g:XkbSwitch['get'], '')`?

**Comment by lumpsoid** [comment]
```
:echo libcall(g:XkbSwitch['backend'], g:XkbSwitch['get'], '')
us
```

**Comment by lumpsoid** [comment]
поменял в OS раскладку с `ru+typewriter` на `ru` – плагин заработал

вот только когда нажимаешь на `Enter` в режиме `insert`, то расскладка два раза переключается:
1. с `ru` на `us`
2. с `us` на `ru`

удалив из списка раскладок `ru` и вернув `ru+typewriter`, плагин снова перестал работать.

но если поменять в параметре:
```
let g:XkbSwitchIMappings = ['ru']
```
на
```
let g:XkbSwitchIMappings = ['ru+typewriter']
```
возникает следующее:
```
Error detected while processing function vimwiki#base#goto_index[33]..vimwiki#base#edit_file[26]..function vimwiki#base#goto_index[33]..vimwiki#base#edit_file[18]..BufRead Autocommands for "*"..function <SNR>23_load_all[6]..<SNR>23_imapping
s_load:
line   26:
E716: Key not present in Dictionary: "ru+typewriter"
```
похоже это означает, что в самом плагине не прописан такой вариант?
для примера переименовав файл, который идет как пример кастомной раскладки, переименовал название расскладки и указал путь:
```
let g:XkbSwitchIMappingsTrData = '/home/qq/.vim/plugged/vim-xkbswitch/xkbswitch.tr'
```
после чего ошибка о том, что нет такого значения в словаре ушло, но вот переключение все равно не происходит.

автоматическое переключение заработало после того как:
1. дописал название раскладки в файл
2. перейдя в `insert mode` сам переключился на русскую расскладку
3. после этого плагин смог заработать

по какой то причине каждый раз заходя в vim, необходимо повторять процедуру с ручным переключением в первый раз, после чего все работает.

но меня немного смущает то, что он 2 раза переключает раскладку каждый раз при нажатии на Enter

м, похоже это сбой из-за другого плагина, они то ли конфликтуют, либо функция другого плагина при нажатии на Enter еще раз перезаходит в `insert mode` что и провоцирует такое поведение.

спасибо за помощь.

**Comment by lumpsoid** [comment]
если кто нибудь в поисках информации когда то сюда забредет, то этот плагин можно устанавливать с помощью [vim-plugin](https://github.com/junegunn/vim-plug)

**Comment by lyokha** [comment]
> 1, дописал название раскладки в файл
> 2. перейдя в insert mode сам переключился на русскую расскладку
> 3. после этого плагин смог заработать

> по какой то причине каждый раз заходя в vim, необходимо повторять процедуру с ручным переключением в первый раз, после чего все работает.

А что вы ожидали в пункте 2? Это нормальное поведение. Плагин *запоминает* предыдущую раскладку, если вы в первый раз вошли в Insert mode, соответственно, ничего не произойдет, так как предыдущей раскладки еще не существует.

> но меня немного смущает то, что он 2 раза переключает раскладку каждый раз при нажатии на Enter
>
> м, похоже это сбой из-за другого плагина, они то ли конфликтуют, либо функция другого плагина при нажатии на Enter еще раз перезаходит в insert mode что и провоцирует такое поведение.

да, возможно это накладка из-за другого плагина, похоже что при вводе Enter происходит временное переключение в нормальный режим и обратно. Что пишет `:imap <Enter>`? (здесь `<Enter>` нужно ввести дословно, т.е. 7 символов вместе с угловыми скобками).

**Comment by lumpsoid** [comment]
> А что вы ожидали в пункте 2? Это нормальное поведение. Плагин запоминает предыдущую раскладку, если вы в первый раз вошли в Insert mode, соответственно, ничего не произойдет, так как предыдущей раскладки еще не существует.
Я пропустил этот момент. Посмотрев еще раз страницу [vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch), не смог найти упоминание этой специфики.
> `:imap <Enter>`
да, один из плагинов использует данную клавишу и выполняет определенный алгоритм действий, что и вызывает данное поведение.

большое спасибо за помощь

**Comment by lyokha** [comment]
Если вы хотите какую-то безусловную раскладку на старте vim, то можете использовать что-то типа

```vim
let g:XkbSwitchILayout = 'ru'
```

где *ru* нужно заменить на правильное имя желаемой раскладки на старте. Но это не основная функциональность плагина, а просто дополнительная фича.
